site_name: Spark

nav:
    - Getting Started: index.md
    - Shapes & Text: shapes_text.md
    - Input: input.md
    - Color: color.md
    - Utilities: utilities.md

theme: 
    name: material
    favicon: img/ignite.ico
    logo: img/Ignite-logo.png
    palette:
        primary: black
        accent: amber

markdown_extensions:
    - pymdownx.keys
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - attr_list
    - pymdownx.highlight:
        linenums: true
        linenums_style: pymdownx.inline
    

site_description: Spark is a library designed to help drawing in python easy

site_author: Schulich Ignite

